config/routes.rb
Rails.application.routes.draw do
  resources :paytm_details
  resources :card_details
  resources :order_details
  resources :orders
  resources :discounts_products
  resources :discounts
  resources :cities
  resources :states
  resources :countries
  resources :product_details
  resources :products
  resources :customers
  resources :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'caller_login',to: 'users#caller_login'
  get 'customer_payment_page',to: 'orders#customer_payment_page'
  get 'product_selling',to: 'products#product_selling'
  get 'single_product_detail',to: 'products#single_product_detail'
  get 'card_details',to: 'products#card_details'
  get 'order',to: 'orders#order'
  get 'search_customer',to: 'customers#search_customer'
  get 'logout',to: 'authentication#logout'
  get 'product_selling_detail' , to:'products#product_selling_detail'
  get 'customer_buy_detail' , to:'products#customer_buy_detail'
  get 'logout' , to:'authentication#logout'
  get 'payment_acknowledgement' , to:'orders#payment_acknowledgement'
  post 'update_order_status' , to:'products#update_order_status'
  post 'authenticate', to: 'authentication#authenticate'
  post 'buy_product', to: 'products#buy_product'
  post 'search_by_phone', to: 'customers#search_by_phone'
  post 'edit_customer_detail', to: 'customers#edit_customer_detail'
  post 'payment', to: 'orders#payment'
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # belongs_to :user
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/discounts_product.rb
class DiscountsProduct < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/paytm_detail.rb
class PaytmDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor_detail
  has_and_belongs_to_many :discounts
  has_many :product_details


  def self.active_product
    return Product.where("available=1")
  end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
  belongs_to :product
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :customers
end

app/controllers/discounts_products_controller.rb
class DiscountsProductsController < ApplicationController
  before_action :set_discounts_product, only: [:show, :edit, :update, :destroy]

  # GET /discounts_products
  # GET /discounts_products.json
  def index
    @discounts_products = DiscountsProduct.all
  end

  # GET /discounts_products/1
  # GET /discounts_products/1.json
  def show
  end

  # GET /discounts_products/new
  def new
    @discounts_product = DiscountsProduct.new
  end

  # GET /discounts_products/1/edit
  def edit
  end

  # POST /discounts_products
  # POST /discounts_products.json
  def create
    @discounts_product = DiscountsProduct.new(discounts_product_params)

    respond_to do |format|
      if @discounts_product.save
        format.html { redirect_to @discounts_product, notice: 'Discounts product was successfully created.' }
        format.json { render :show, status: :created, location: @discounts_product }
      else
        format.html { render :new }
        format.json { render json: @discounts_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts_products/1
  # PATCH/PUT /discounts_products/1.json
  def update
    respond_to do |format|
      if @discounts_product.update(discounts_product_params)
        format.html { redirect_to @discounts_product, notice: 'Discounts product was successfully updated.' }
        format.json { render :show, status: :ok, location: @discounts_product }
      else
        format.html { render :edit }
        format.json { render json: @discounts_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts_products/1
  # DELETE /discounts_products/1.json
  def destroy
    @discounts_product.destroy
    respond_to do |format|
      format.html { redirect_to discounts_products_url, notice: 'Discounts product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discounts_product
      @discounts_product = DiscountsProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discounts_product_params
      params.require(:discounts_product).permit(:discount_id, :product_id, :status)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/discounts_products_helper.rb
module DiscountsProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discounts_products/_form.html.erb
<%= form_for(discounts_product) do |f| %>
  <% if discounts_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discounts_product.errors.count, "error") %> prohibited this discounts_product from being saved:</h2>

      <ul>
      <% discounts_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discount_id %>
    <%= f.number_field :discount_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounts_products/edit.html.erb
<h1>Editing Discounts Product</h1>

<%= render 'form', discounts_product: @discounts_product %>

<%= link_to 'Show', @discounts_product %> |
<%= link_to 'Back', discounts_products_path %>

app/views/discounts_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discounts Products</h1>

<table>
  <thead>
    <tr>
      <th>Discount</th>
      <th>Product</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts_products.each do |discounts_product| %>
      <tr>
        <td><%= discounts_product.discount_id %></td>
        <td><%= discounts_product.product_id %></td>
        <td><%= discounts_product.status %></td>
        <td><%= link_to 'Show', discounts_product %></td>
        <td><%= link_to 'Edit', edit_discounts_product_path(discounts_product) %></td>
        <td><%= link_to 'Destroy', discounts_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discounts Product', new_discounts_product_path %>

app/views/discounts_products/new.html.erb
<h1>New Discounts Product</h1>

<%= render 'form', discounts_product: @discounts_product %>

<%= link_to 'Back', discounts_products_path %>

app/views/discounts_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount:</strong>
  <%= @discounts_product.discount_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @discounts_product.product_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @discounts_product.status %>
</p>

<%= link_to 'Edit', edit_discounts_product_path(@discounts_product) %> |
<%= link_to 'Back', discounts_products_path %>