config/routes.rb
Rails.application.routes.draw do
  resources :paytm_details
  resources :card_details
  resources :order_details
  resources :orders
  resources :discounts_products
  resources :discounts
  resources :cities
  resources :states
  resources :countries
  resources :product_details
  resources :products
  resources :customers
  resources :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'caller_login',to: 'users#caller_login'
  get 'customer_payment_page',to: 'orders#customer_payment_page'
  get 'product_selling',to: 'products#product_selling'
  get 'single_product_detail',to: 'products#single_product_detail'
  get 'card_details',to: 'products#card_details'
  get 'order',to: 'orders#order'
  get 'search_customer',to: 'customers#search_customer'
  get 'logout',to: 'authentication#logout'
  get 'product_selling_detail' , to:'products#product_selling_detail'
  get 'customer_buy_detail' , to:'products#customer_buy_detail'
  get 'logout' , to:'authentication#logout'
  get 'payment_acknowledgement' , to:'orders#payment_acknowledgement'
  post 'update_order_status' , to:'products#update_order_status'
  post 'authenticate', to: 'authentication#authenticate'
  post 'buy_product', to: 'products#buy_product'
  post 'search_by_phone', to: 'customers#search_by_phone'
  post 'edit_customer_detail', to: 'customers#edit_customer_detail'
  post 'payment', to: 'orders#payment'
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # belongs_to :user
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/discounts_product.rb
class DiscountsProduct < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/paytm_detail.rb
class PaytmDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor_detail
  has_and_belongs_to_many :discounts
  has_many :product_details


  def self.active_product
    return Product.where("available=1")
  end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
  belongs_to :product
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :customers
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:state_name, :country_id, :status)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/states/_form.html.erb
<%= form_for(state) do |f| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state_name %>
    <%= f.text_field :state_name %>
  </div>

  <div class="field">
    <%= f.label :country_id %>
    <%= f.number_field :country_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>State name</th>
      <th>Country</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.state_name %></td>
        <td><%= state.country_id %></td>
        <td><%= state.status %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State name:</strong>
  <%= @state.state_name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @state.country_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @state.status %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>