config/routes.rb
Rails.application.routes.draw do
  resources :paytm_details
  resources :card_details
  resources :order_details
  resources :orders
  resources :discounts_products
  resources :discounts
  resources :cities
  resources :states
  resources :countries
  resources :product_details
  resources :products
  resources :customers
  resources :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'caller_login',to: 'users#caller_login'
  get 'customer_payment_page',to: 'orders#customer_payment_page'
  get 'product_selling',to: 'products#product_selling'
  get 'single_product_detail',to: 'products#single_product_detail'
  get 'card_details',to: 'products#card_details'
  get 'order',to: 'orders#order'
  get 'search_customer',to: 'customers#search_customer'
  get 'logout',to: 'authentication#logout'
  get 'product_selling_detail' , to:'products#product_selling_detail'
  get 'customer_buy_detail' , to:'products#customer_buy_detail'
  get 'logout' , to:'authentication#logout'
  get 'payment_acknowledgement' , to:'orders#payment_acknowledgement'
  post 'update_order_status' , to:'products#update_order_status'
  post 'authenticate', to: 'authentication#authenticate'
  post 'buy_product', to: 'products#buy_product'
  post 'search_by_phone', to: 'customers#search_by_phone'
  post 'edit_customer_detail', to: 'customers#edit_customer_detail'
  post 'payment', to: 'orders#payment'
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # belongs_to :user
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/paytm_detail.rb
class PaytmDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor_detail
  has_and_belongs_to_many :discounts
  has_many :product_details


  def self.active_product
    return Product.where("available=1")
  end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
  belongs_to :product
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :customers
end

app/controllers/card_details_controller.rb
class CardDetailsController < ApplicationController
  before_action :set_card_detail, only: [:show, :edit, :update, :destroy]

  # GET /card_details
  # GET /card_details.json
  def index
    @card_details = CardDetail.all
  end

  # GET /card_details/1
  # GET /card_details/1.json
  def show
  end

  # GET /card_details/new
  def new
    @card_detail = CardDetail.new
  end

  # GET /card_details/1/edit
  def edit
  end

  # POST /card_details
  # POST /card_details.json
  def create
    @card_detail = CardDetail.new(card_detail_params)

    respond_to do |format|
      if @card_detail.save
        format.html { redirect_to @card_detail, notice: 'Card detail was successfully created.' }
        format.json { render :show, status: :created, location: @card_detail }
      else
        format.html { render :new }
        format.json { render json: @card_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_details/1
  # PATCH/PUT /card_details/1.json
  def update
    respond_to do |format|
      if @card_detail.update(card_detail_params)
        format.html { redirect_to @card_detail, notice: 'Card detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_detail }
      else
        format.html { render :edit }
        format.json { render json: @card_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_details/1
  # DELETE /card_details/1.json
  def destroy
    @card_detail.destroy
    respond_to do |format|
      format.html { redirect_to card_details_url, notice: 'Card detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_detail
      @card_detail = CardDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_detail_params
      params.require(:card_detail).permit(:cust_id, :card_number, :expiry_date, :cvc_code, :cardholder_name, :status)
    end
end

app/helpers/card_details_helper.rb
module CardDetailsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card_details/_form.html.erb
<%= form_for(card_detail) do |f| %>
  <% if card_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_detail.errors.count, "error") %> prohibited this card_detail from being saved:</h2>

      <ul>
      <% card_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cust_id %>
    <%= f.number_field :cust_id %>
  </div>

  <div class="field">
    <%= f.label :card_number %>
    <%= f.text_field :card_number %>
  </div>

  <div class="field">
    <%= f.label :expiry_date %>
    <%= f.text_field :expiry_date %>
  </div>

  <div class="field">
    <%= f.label :cvc_code %>
    <%= f.text_field :cvc_code %>
  </div>

  <div class="field">
    <%= f.label :cardholder_name %>
    <%= f.text_field :cardholder_name %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/card_details/edit.html.erb
<h1>Editing Card Detail</h1>

<%= render 'form', card_detail: @card_detail %>

<%= link_to 'Show', @card_detail %> |
<%= link_to 'Back', card_details_path %>

app/views/card_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Card Details</h1>

<table>
  <thead>
    <tr>
      <th>Cust</th>
      <th>Card number</th>
      <th>Expiry date</th>
      <th>Cvc code</th>
      <th>Cardholder name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_details.each do |card_detail| %>
      <tr>
        <td><%= card_detail.cust_id %></td>
        <td><%= card_detail.card_number %></td>
        <td><%= card_detail.expiry_date %></td>
        <td><%= card_detail.cvc_code %></td>
        <td><%= card_detail.cardholder_name %></td>
        <td><%= card_detail.status %></td>
        <td><%= link_to 'Show', card_detail %></td>
        <td><%= link_to 'Edit', edit_card_detail_path(card_detail) %></td>
        <td><%= link_to 'Destroy', card_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card Detail', new_card_detail_path %>

app/views/card_details/new.html.erb
<h1>New Card Detail</h1>

<%= render 'form', card_detail: @card_detail %>

<%= link_to 'Back', card_details_path %>

app/views/card_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cust:</strong>
  <%= @card_detail.cust_id %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @card_detail.card_number %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @card_detail.expiry_date %>
</p>

<p>
  <strong>Cvc code:</strong>
  <%= @card_detail.cvc_code %>
</p>

<p>
  <strong>Cardholder name:</strong>
  <%= @card_detail.cardholder_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @card_detail.status %>
</p>

<%= link_to 'Edit', edit_card_detail_path(@card_detail) %> |
<%= link_to 'Back', card_details_path %>